# Nginx configuration file to serve static contents from different directories based on URL patterns, using location blocks.
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        # Location block is used for routing requests based on URI patterns, In this URLs starting with / and /images/ are handled differently.
        location / {
            root /data/www;
        }

        location /images/ {
            alias /data/data/;
        }
    }
}