worker_processes auto;

events { 
    worker_connections 1024;
}

http {
    upstream api_1 {
        server load-balancer-first-api-1:3000;
        server load-balancer-first-api-2:3000;
    }

    upstream api_2 {
        server load-balancer-second-api-1:3000;
        server load-balancer-second-api-2:3000;
    }

    server {
        listen 80;
        server_name _;

        # GLOBAL proxy config such as --> auth, body, header
        auth_request /auth;
        proxy_set_body $request_body;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        location /api-1/ {
            proxy_pass http://api_1/;
        }

        location /api-2/ {
            proxy_pass http://api_2/;
        }

        location = /auth {
            internal;
            auth_request off;
            
            proxy_pass http://load-balancer-auth-1:3000/auth;

            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }
    }
}