worker_processes auto;

events { 
    worker_connections 1024;
}

http {
    upstream api {
        server simple-proxy-server-api-1:3000;
        server simple-proxy-server-api-2:3000;
        server simple-proxy-server-api-3:3000;
    }

    server {
        listen 80;
        server_name example.com;


        location / {
            proxy_pass http://api;
            proxy_set_body $request_body;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
     }
}