worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;

        ssl_certificate /cert/certificate.crt;
        ssl_certificate_key /cert/privatekey.key;

        location / {
            root /website/website;
            index index.html;
            try_files $uri $uri/ /index.html; 
        }

        location /images/ {
            alias /website/images/;
            try_files $uri /images/1.jpg;
        }
    }
}